### ISSUE TITLE
pip._vendor.pkg_resources is deprecated

### ISSUE THREAD

**Issue by MariaHei** [quantling/discriminative_lexicon_model#1]
Hi :) The way your __init__.py is currently setup is deprecated (see [here](https://setuptools.pypa.io/en/latest/pkg_resources.html)). Can you update that? It creates problems for automatic testing in my github actions :)

**Comment by msaito8623** [comment]
Hi :) I fixed __init__.py, regarding the deprecation. There may still be some deprecations that need to be updated. Please let me know in case you find some more. Thanks! :D

**Comment by MariaHei** [comment]
Wow that was fast! I'll try it :)
